// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = import.meta.glob<Record<string, unknown>>("../components/mockups/**/*.tsx");
